export { default as Home } from './Home'
export { default as Navbar } from './Navbar'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as ApplyDoctor } from './ApplyDoctor'
export { default as MakeAppointment } from './MakeAppointment'
export { default as Profile } from './Profile'